# Generated by Django 3.0 on 2021-01-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
